/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author dangh
 */
public class Function_Tour_Dulich extends javax.swing.JPanel {
    Font defaultFont = new Font("Arial",Font.BOLD,18);
    Color textColor = Color.decode("#ffffff");
    Color backgroundColor = Color.decode("#000000");
    Color hoverColor = Color.decode("#00aced");
    
    public Function_Tour_Dulich() {
        initComponents();
    }
    public JPanel Tour_Dulich_FunctionCreate(){
        
        
        
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(4, 2, 10 ,10 ));
        panel.setPreferredSize(new Dimension(400,400));
        
        JButton bt1 = new JButton("DANH SÁCH KHÁCH HÀNG");
        bt1.setFont(defaultFont);
        bt1.setForeground(textColor);
        bt1.setBackground(backgroundColor);
        MouseListener bt1_mouse = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                
            }
            @Override
            public void mouseEntered(MouseEvent me) {
                bt1.setBackground(hoverColor);
            }
            @Override
            public void mouseExited(MouseEvent me) {
                bt1.setBackground(backgroundColor);
            }
        };
        bt1.addMouseListener(bt1_mouse);
        
        
        JButton bt2 = new JButton("DANH SÁCH CÁC ĐỊA ĐIỂM");
        bt2.setFont(defaultFont);
        bt2.setForeground(textColor);
        bt2.setBackground(backgroundColor);
        MouseListener bt2_mouse = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                
            }
            @Override
            public void mouseEntered(MouseEvent me) {
                bt2.setBackground(hoverColor);
            }
            @Override
            public void mouseExited(MouseEvent me) {
                bt2.setBackground(backgroundColor);
            }
        };
        bt2.addMouseListener(bt2_mouse);
        
        
        JButton bt3 = new JButton("THỐNG KÊ");
        bt3.setFont(defaultFont);
        bt3.setForeground(textColor);
        bt3.setBackground(backgroundColor);
        MouseListener bt3_mouse = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                
            }
            @Override
            public void mouseEntered(MouseEvent me) {
                bt3.setBackground(hoverColor);
            }
            @Override
            public void mouseExited(MouseEvent me) {
                bt3.setBackground(backgroundColor);
            }
        };
        bt3.addMouseListener(bt3_mouse);
        
        JButton bt4 = new JButton("DOANH THU");
        bt4.setFont(defaultFont);
        bt4.setForeground(textColor);
        bt4.setBackground(backgroundColor);
        MouseListener bt4_mouse = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                
            }
            @Override
            public void mouseEntered(MouseEvent me) {
                bt4.setBackground(hoverColor);
            }
            @Override
            public void mouseExited(MouseEvent me) {
                bt4.setBackground(backgroundColor);
            }
        };
        bt4.addMouseListener(bt4_mouse);
        
        panel.add(bt1);
        panel.add(bt2);
        panel.add(bt3);
        panel.add(bt4);
        return panel;
    }
    public JPanel Tour_Dulich_ImageCreate(){
        JPanel image = new JPanel();
        image.setLayout(null);
        image.setPreferredSize(new Dimension(400, 400));
        image.setBackground(Color.pink);
        return image;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
