/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author dangh
 */
public class Function_Tour_Dulich extends javax.swing.JPanel {
    
    public Function_Tour_Dulich() {
        initComponents();
    }
    public JPanel Tour_Dulich_FunctionCreate(){
        Font defaultFont = new Font("Arial",Font.BOLD,18);
        Color textColor = Color.decode("#ffffff");
        Color backgroundColor = Color.decode("#000000");
        Color hoverColor = Color.decode("#00aced");
        
        JPanel panel = new JPanel();
        JButton bt1 = new JButton("DANH SÁCH KHÁCH HÀNG");
        bt1.setForeground(textColor);
        bt1.setBackground(backgroundColor);
        bt1.setPreferredSize(new Dimension(200, 40));
        bt1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                
            }
            @Override
            public void mouseEntered(MouseEvent me) {
                bt1.setBackground(hoverColor);
            }
            @Override
            public void mouseExited(MouseEvent me) {
                bt1.setBackground(backgroundColor);
            }
        });
        JButton bt2 = new JButton("Lập danh sách các địa điểm");
        bt2.setForeground(textColor);
        bt2.setBackground(backgroundColor);
        bt2.setPreferredSize(new Dimension(200, 40));
        bt2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                
            }
            @Override
            public void mouseEntered(MouseEvent me) {
                bt2.setBackground(hoverColor);
            }
            @Override
            public void mouseExited(MouseEvent me) {
                bt2.setBackground(backgroundColor);
            }
        });
        JButton bt3 = new JButton("Lập tour mới");
        bt3.setForeground(textColor);
        bt3.setBackground(backgroundColor);
        bt3.setPreferredSize(new Dimension(200, 40));
        bt3.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                JFrame_AddTour add_tour = new JFrame_AddTour();
                new JFrame_AddTour().setVisible(true);
                
            }
            @Override
            public void mouseEntered(MouseEvent me) {
                bt3.setBackground(hoverColor);
            }
            @Override
            public void mouseExited(MouseEvent me) {
                bt3.setBackground(backgroundColor);
            }
        });
        panel.add(bt1);
        panel.add(bt2);
        panel.add(bt3);
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
