/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author dangh
 */
public class Tour_Dulich_Function extends javax.swing.JPanel {

    /**
     * Creates new form Tour_Dulich_Function
     */
    public Tour_Dulich_Function() {
        initComponents();
    }
    public JPanel Tour_Dulich_FunctionCreate(){
        JPanel panel = new JPanel();
        JButton bt1 = new JButton("Lập danh sách khách hàng");
        bt1.setPreferredSize(new Dimension(200, 40));
        JButton bt2 = new JButton("Lập danh sách các địa điểm");
        bt2.setPreferredSize(new Dimension(200, 40));
        JButton bt3 = new JButton("Thống kê chi phí");
        bt3.setPreferredSize(new Dimension(200, 40));
        panel.add(bt1);
        panel.add(bt2);
        panel.add(bt3);
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
