/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author dangh
 */
public class Doan_Khach_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Doan_Khach_Panel
     */
    public Doan_Khach_Panel() {
        initComponents();
    }
    public JPanel Doan_Khach_TableCreate(){
        JPanel panel = new JPanel();
        panel.setPreferredSize(new Dimension(1200,1000));
        panel.setBackground(Color.blue);
        JTable table = new JTable(6,6);
        table.setRowHeight(30);
        JScrollPane sp = new JScrollPane(table);
        sp.setPreferredSize(new Dimension(900, 900));
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i=0 ; i < table.getColumnCount() ; i++){
            table.getColumnModel().getColumn(i).setPreferredWidth(200);
        }
        panel.add(sp);
        panel.setVisible(true);
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
